### ISSUE TITLE
How to custom item view?

### ISSUE THREAD

**Issue by Widiyanto** [jakebonk/DraggableTreeViewExample#3]

**Comment by jakebonk** [comment]
You can do so by creating an adapter that extends extends TreeViewAdapter. Look at the SimpleTreeVieeAdapter as an example. 
https://github.com/jakebonk/DraggableTreeView/blob/master/draggabletreeview/src/main/java/com/allyants/draggabletreeview/SimpleTreeViewAdapter.java
