### ISSUE TITLE
How implement on Fragment ?

### ISSUE THREAD

**Issue by adeds** [jakebonk/DraggableTreeViewExample#4]
hello sir, i need your help with this,
i have problem when i implement on fragment, but its fine when i implement in activity.
what should i fill on adapter first parameter ?

this is my code : 
public class CategorySubFragment extends Fragment {
    private FloatingActionButton fabAddCategory;
    public static ArrayList<ModCategory> arrayCategory;
    private DraggableTreeView draggableTreeView;

    public CategorySubFragment() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_category_sub, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        fabAddCategory = view.findViewById(R.id.fab_add_category);
        draggableTreeView = (DraggableTreeView)view.findViewById(R.id.d_tree_view);

        TreeNode root = new TreeNode(this);
        TreeNode item = new TreeNode("Item 1");
        TreeNode item2 = new TreeNode("Item 2");
        TreeNode subitem = new TreeNode("Sub Item 2");

        subitem.addChild(new TreeNode("Sub Sub Item 1"));

        item.addChild(subitem);
        item.addChild(new TreeNode("Sub Item 1"));
        root.addChild(new TreeNode("Item 3"));
        root.addChild(new TreeNode("Item 4"));
        root.addChild(new TreeNode("Item 5"));
        root.addChild(new TreeNode("Item 6"));
        root.addChild(new TreeNode("Item 7"));
        root.addChild(new TreeNode("Item 8"));
        root.addChild(new TreeNode("Item 9"));
        root.addChild(new TreeNode("Item 10"));
        root.addChild(new TreeNode("Item 11"));
        root.addChild(new TreeNode("Item 12"));
        root.addChild(item2);
        root.addChild(item);
        SimpleTreeViewAdapter adapter = new SimpleTreeViewAdapter(getActivity().getApplicationContext(), root);
        draggableTreeView.setAdapter(adapter);

        arrayCategory = new ArrayList<>();

        ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle(getResources().getString(R.string.category));

        fabAddCategory.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //startActivityForResult(new Intent(getContext(), AddCategoryActivity.class), REQ_CODE_ADD_CAT);
                startActivityForResult(new Intent(getContext(), AddCategory.class), REQ_CODE_ADD_CAT);
            }
        });
    }

and this is my error : 

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.addView(android.view.View)' on a null object reference
        at com.allyants.draggabletreeview.DraggableTreeView.createTreeItem(DraggableTreeView.java:445)
        at com.allyants.draggabletreeview.DraggableTreeView.inflateViews(DraggableTreeView.java:111)
        at com.allyants.draggabletreeview.DraggableTreeView.inflateViews(DraggableTreeView.java:117)
        at com.allyants.draggabletreeview.DraggableTreeView.notifyDataSetChanged(DraggableTreeView.java:105)
        at com.allyants.draggabletreeview.DraggableTreeView.setAdapter(DraggableTreeView.java:98)
        at com.batavianet.aipos.ui.main.item.category.CategorySubFragment.onViewCreated(CategorySubFragment.java:76)

this error showed on : 
 draggableTreeView.setAdapter(adapter);

thankyou, love your works

**Comment by jakebonk** [comment]
Sorry for such a late response! A quick fix could be to pass in the context from your base activity instead of passing the context from the fragment. So try calling 
TreeNode root = new TreeNode(getActivity());

Hope this works!
